function FG_label_multiple_areas_and_separate_clusters
% label the mutiple_areas' ROI img into different an img in which different areas is marked in different nums. 
% this can be used to handle the mask img generated by rest_sliceviewer's  "save clusters" function
  if strcmp(spm('ver',[],1),'SPM5')||strcmp(spm('ver',[],1),'SPM8')
       Filename = spm_select(inf,'any','Select the image to be read', [],pwd,'.*img$|.*nii$');
  else  
       Filename = spm_get(inf,'any','Select the image to be read'); 
  end
 if isempty(Filename)
     return
 end
  
V1=spm_vol(Filename); % 
[k1,l1]=spm_read_vols(V1); % 

[mask,num_clusters]=bwlabeln(k1,18); %  excellent funtion
% num_clusters=max(max(max(mask)));
fprintf(1,'this ROI has %2.0f clusters\n\n',num_clusters)

[Path,Name,Ext,Versn] = fileparts(Filename);
V1.fname=fullfile(Path, ['labeled_' Name Ext]);
%   Vmat.pinfo(1)=1;
   V1.dt(1)=16;  %% very very important, otherwise, the value of the final img will be wrong
   
   V1=spm_write_vol(V1, mask);
fprintf('Clusters labeling done~~~\n\n')

h=questdlg('Do you want to separate different clusters into independent images?','Separate files...','Yes','No','Yes');
if strcmp(h,'Yes')
   for i=1: num_clusters
       mask_tem=mask;
       V1.fname=fullfile(Path, ['labeled_' Name,'cluster_' num2str(i) Ext ]);
       V1.dt(1)=16;  %% very very important, otherwise, the value of the final img will be wrong
       mask_tem(find(mask_tem~=i))=0;
       V1=spm_write_vol(V1, mask_tem);
   end
 
    
fprintf('Total %d Clusters separating is done~~~\n\n',num_clusters)    
end


