% Welcome to use this <fmri_grocer> tool kits.
% 3. About this toolbox 
% To run this toolbox smoothly, at least you need to add SPM5(or SPM8) into your MATLAB path. If you want to use some functions about ROI stuff, you also need to add MarsBar (http://marsbar.sourceforge.net/) into your MATLAB path. Apart from these two main packages, I think I have integrated all other necessary functions int my own package. 
% This toolbox was designed to liberate data analysts from the boring and repeating setup stuffs in SPM. This toolbox can facilitate your data analysis with SPM, and avoid some intentioned mistakes during your repeating setup progress. Some batch generator here may just be able to produce some basic specification of the model, if you want to specify some other complicated settings, you can modify the produced batch scripts manually or modify them in SPM8 Batch Editor directly after importing them into it. 
% 4. How to organize data for this toolbox 
% Important: it is recommended to organize your data directories as below which are the most efficient way to organize data for this toolbox. 
                    % - fMRI study root path
                        %   - - functional_group1_Data
                            %     - - subj_1
                            %       - - vol_001.nii   
                            %       - - vol_002.nii
                            %       - - ...
                            %     - - subj_2
                            %       - - vol_001.nii
                            %       - - vol_002.nii
                            %       - - ...
                            %     - - subj_n
                            %       - - ...
                        %   - - functional_group2_Data
                            %     - - subj_1
                            %       - - vol_001.nii    
                            %       - - vol_002.nii
                            %       - - ...
                            %     - - subj_2
                            %       - - vol_001.nii
                            %       - - vol_002.nii
                            %       - - ...
                            %     - - subj_n
                            %       - - ...
                        %   - - functional_group3_Data
                            %     - - ... 
                        %   - - Anatomy-data
                            %     - - t1_subj_001.nii      
                            %     - - t1_subj_002.nii
                            %     - - ...
%
%
%
function fmri_grocer
clc  
warning off all
a=which('fmri_grocer');
[a,b,c,d]=FG_fileparts(a);
addpath(genpath(a));
% fmri_grocer version
FGver = '2.17';  % SPM8-based
FGaut ='Senhua Zhu';

% welcome~~
fprintf('\n');
fprintf( ' >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n');
fprintf( '   >>>>      Welcome to utilize  Grocer toolbox V%s (SPM5/8 based)        <<<<\n',FGver);
fprintf( '   >>>>              By <a href="http://code.google.com/p/fmrigrocer/">Senhua Zhu</a>, @CFN, UPenn Med. 09/2011                <<<<\n');
fprintf( '   >>>>                       QQ group #: 60524357                          <<<<\n');
fprintf('   >>>>    ....... http://www.fil.ion.ucl.ac.uk/spm/ext/#Grocer ........    <<<<\n');
fprintf(['   >>>>                    < You have installed ',spm('Ver'),' >                      <<<<\n']);
fprintf( '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n');


%%
% only allow one instance of this toolbox
hdl=findobj('Tag','fmri_grocer');
if ~isempty(hdl)
    close (hdl)
    clear hdl
end

%-Open startup window, set window defaults
%-Get size and scalings and create Menu window

S = get(0,'ScreenSize');
if all(S==1), error('Can''t open any graphics windows...'), end

[WS FS PF Rect bno bgapr bh gh by bx bw]=Exec_getwinDef;

%-Draw fmri_grocer window
Fig_handle = figure( ...
    'IntegerHandle','off',...
	'Name',['fMRI Grocer V' FGver],...
	'NumberTitle','off',...
	'Tag','fmri_grocer',...
	'Position',Rect.*WS,...
	'Resize','off',...
	'Color',[1 1 1]*.6,...
	'UserData',struct('FGver',FGver,'FGaut',FGaut),...
	'MenuBar','none',...
	'DefaultTextFontName',PF.helvetica,...
	'DefaultTextFontSize',FS(6),...
	'DefaultUicontrolFontName',PF.times,...
	'DefaultUicontrolFontSize',FS(11),...
	'DefaultUicontrolInterruptible','on',...
	'Renderer','painters',...
	'Visible','off' ...
    );

%- Setting up PopUp menus functions and lists for "Callback"
%=======================================================================
% menu 1
line_n=1;

f_preprocess={
'FG_slicetiming_gen',...
'FG_realign_gen',...
'FG_coreg_gen',...
'FG_smooth_all_gen',...
'FG_self_masked_smoothing',...
'FG_segment_gen',...
'FG_norm_T1_estimate_gen',...
'FG_norm_T1_write_gen',...
'FG_norm_write_MeanCBF_gen',...
'FG_norm_write_allSmoothedFun_gen',...
'FG_norm_write_mean_allSmoothedFun_gen',...
'FG_norm_write_all_T1_MeanCBF_SmoothedFun_gen',...
'FG_norm_est_and_write_mean_T1_gen',...
'FG_norm_est_and_write_T1_smoothed_gen',...
'FG_all_preprocessing_pipeline_gen',...
'FG_enhanced_all_preprocessing_pipeline_gen', ...
'FG_pca_denoising_after_motion_filter' ,...
};

L_preprocess=[
[num2str(line_n) '. SPM8 Preprocess batch (n-Group-Subj)...'],...
'|  - Slice timing (Est. & reslice)'...
'|  - Realgin (Est. & reslice)'...
'|  - Coregister (Est.)'...
'|  - Smooth with Kernel',...
'|  - Smooth images with self-masking',...
'|  - Segment T1s',...
'|  - Normalize (Est: T1)',...
'|  - Normalize (Write: T1)',...
'|  - Normalize (Write: mean Img)',...
'|  - Normalize (Write: Smoothed Img)',...
'|  - Normalize (Write: mean-Smoothed Img)',...
'|  - Normalize (Write: T1-mean-Smoothed Img)',...
'|  - Normalize (Est.& write: T1-mean Img)',...
'|  - Normalize (Est.& write: T1-Smoothed Img)',...
'|  * Create a pipeline for standard preprocessing ',...
'|  * Do the (enhanced)-preprocessing & CBF Calc.',...
'|  - PCA-denoising for MRI images(No binarizeds)', ...
];

line_n=line_n+1;

% menu 2
f_statistic={
'FG_1st_level_gen',...
'FG_gen_MultiBlock_design_matrix',...
'FG_fullfactorial_2nd_gen',...
'FG_pair_ttest_2nd_gen',...
'FG_twoSample_ttest_2nd_gen',...
'FG_oneSample_ttest_2nd_gen',...
'FG_create_multiple_oneSample_ttest_2nd_gen',...
'FG_clear_files_under_selected_folders_for_RE_Estimation',...
'FG_run_all_design_jobs_under_folders',...
'FG_estimate_all_gen',...
'FG_contrast_all_T_F_gen',...
'Edit FG_T_names_contrasts',...
'Edit FG_F_names_contrasts',...
'FG_result_all_gen',...
'FG_category_all_Cons_in_1stLevel',...
'FG_remove_all_contrasts_and_files',...
};

L_statistic=[
[num2str(line_n) '. SPM8 Statistic batch...'],...
'|  - 1st level design',...
'|  - - - Create the Onsets(Scans).mat file for block design',...
'|  - Full factorial design (2nd_level)',...
'|  - Pair_T-test (2nd_level)',...
'|  - Two Sample T-test (2nd_level)',...
'|  - One Sample T-test (2nd_level)',...
'|  - - Create One-Sample ttest batches for multiple groups',...
'|  - - - Clear files under-folder files for Re-Estimation',...
'|  - Run all design jobs under Output-folders',...
'|  - Estimate all SPM.mat',...
'|  - Contrast all SPM.mat',...
'|  - - - Edit T_contrasts template',...
'|  - - - Edit F_contrasts template',...
'|  - Result all SPM.mat',...
'|  - Categorize all Con*.img after 1st_level',...
'|  - Remove all contrasts from SPM.mat',...
];

line_n=line_n+1;

% menu 3
f_CBF={
'FG_ASL_CBF_reconstruction',...
'FG_corr2FisherZ_within_mask',...
'FG_img2zScore_img',...
'FG_img2zScore_img_multipleSubjects',...
'FG_grandmean_scale_CBF_in_ROI',...
'FG_copy_all_wMeanCBF',...
'FG_PVE_correction_for_perfusiondata',...
'FG_PVE_correction_for_perfusiondata_multiImgs_eachSubj',...
'FG_Voxelwise_variance_calculation',...
'FG_Voxelwise_Pearson_correlation',...
'FG_Voxelwise_ICC_improved',...
'FG_ICC_for_vectors',...
'FG_correlation_cofficient_comparison',...
'FG_correlation_cofficient_comparison_for_vectors',...
'FG_singledir_regress_out_TagControl',...
'FG_MultiG_regress_out_TagControl',...
};

L_CBF=[
[num2str(line_n) '. CBF(ASL-based) related...'],...
'|  * CBF calculation (SPM5/8,n-Group-Subj)',...
'|  - Cofficient(r) 2 Fisher''s Z Within mask',...
'|  - Img 2 zScore_Img',...
'|  - Img 2 zScore_Img (n-Subj)',...
'|  - Grandmean scale CBF Imgs (voxel*100/Grandmean)',...
'|  * Copy (w)MeanCBF into a folder (n-Group-Subj)',...
'|  - Do PVE-correction for the MeanCBFs',...
'|  - Do PVE-correction for the CBFs (n-Group-Subj)',...
'|  - Voxel-wise group variance (a groups of imgs)',...
'|  - Voxel-wise Pearson''s r (two groups of imgs)',...
'|  - Voxel-wise ICC across (n groups of imgs)',...
'|  - ICC calculation of multiple matrixes',...
'|  - - - z-test two imgs of r(corr. cofficient)',...
'|  - - - z-test two vectors of r(corr. cofficient)',...
'|  - Regress Tag-Ctrl from perfusion imgs',...
'|  - Regress Tag-Ctrl from perfusion imgs (n-Group-Subj)',...
];

line_n=line_n+1;

% menu 4
f_ROI={
'FG_get_meanCBF_TC_in_ROIs_singlesubDir',... 
'FG_get_meanCBF_TC_in_ROIs_multiple_subDirs_into1file',... 
'FG_get_SD_TC_in_ROIs_singlesubDir',... 
'FG_get_SD_TC_in_ROIs_multiple_subDirs_into1file',... 
'FG_Plot_TCs',...
'FG_Plot_TCs_overlay',...
'FG_fc_1subj',...
'FG_fc_ngroup_nSubjs',...
'FG_imgHistogram',...
'FG_AAL_90areas_TC_extract_DPARSFA_based',...
'FG_AAL_116areas_TC_extract_DPARSFA_based',...
'[a,b,c,d]=FG_fileparts(which(''fmri_grocer''));edit([a filesep ''Templates'' filesep ''aal.nii.txt''])',...
'FG_read_the_name_of_AAL_list',...
'edit(''FG_AAL_names_list.m'')',...
'FG_Brodmann_48areas_TC_extract',...
'FG_BA_or_AAL_areas_combination',...
'FG_batch_MNI2SphereROI_build_marsbar_based',...
'FG_label_multiple_areas_and_separate_clusters',...
'FG_Binary_multiple_labeling_ROI',...
'FG_get_totals' ,...
'FG_evaluate_ROI_overlay' ,...
};

L_ROI=[
[num2str(line_n) '. ROI related...'],...
'|  - Get TimeCourse of ROIs of Selected Imgs',...
'|  - Get TC of ROIs of all Imgs under folders',...
'|  - Get SD-TC of ROIs of Selected Imgs',...
'|  - Get SD-TC of ROIs of all Imgs under folders',...
'|  - Plot Time Courses in txt/mat/csv file(Separately)',...
'|  - Plot Time Courses in txt/mat/csv file(Overlay)',...
'|  - Do functional connectivity(1 Subj)',...
'|  - Do functional connectivity(n-Group-Subj)',...
'|  - Show histogram of Imgs within a mask',...
'|  - Extract AAL(61x73x61,90areas)''s TC',...
'|  - Extract AAL(61x73x61,116areas)''s TC',...
'|  - - - Show the AAL regions list',...
'|  - Inquire AAL regions list',...
'|  - - - Edit your AAL regions list',...
'|  - Extract Brodmann(61x73x61,48areas)''s TC',...
'|  - BA/AAL multi. Labeling areas combination',...
'|  - MNI Coordinate(*.txt) 2 Sphere_ROI',...
'|  - Label clusters into numbers and separate clusters',...
'|  - Binarize multiple labeling ROIs',...
'|  - Get volumes of the selected images (ml)',...
'|  - Evaluate overlay between two groups of ROIs',... 
];

line_n=line_n+1;

% menu 5
f_Coordinate = {
'FG_calculate_averageXYZ',...
'FG_find_peak_voxel',...
'FG_icbm_spm2tal',...
'FG_mni2tal',...
'FG_mni2vox',...
'FG_tal2icbm_spm',...
'FG_tal2mni',...
'FG_vox2mni',...
'FG_voxel_coord_AAL_region_inqury',...
'FG_mni_coord_AAL_region_inqury',...
};

L_Coordinate=[
[num2str(line_n) '. Coordinate related...'],...
'|  - Get the central Coordinate of a cluster',...
'|  - Find the peak voxels within a mask',...
'|  - MNI(ICBM) 2 Tal',...
'|  - MNI 2 Tal',...
'|  - MNI 2 Voxel Space',...
'|  - Tal 2 MNI(ICBM)',...
'|  - Tal 2 MNI',...
'|  - Voxel Space 2 MNI',...
'|  - Inquire Voxel Space Coord. in AAL',...
'|  - Inquire MNI Coord. in AAL',...
];

line_n=line_n+1;

% menu 6
FGformat={
'FG_batch_Nii2NiftiPairs',...
'FG_batch_NiftiPairs2Nii',...
'FG_batch_cluster_img2mat_marsbar_based_cliff',...
'FG_batch_rois_mat2img_marsbar_based_cliff',...
'FG_get_nii_frame',...
'FG_unzip_gz_files',...
'FG_zip_files_as_gz',...
'FG_separate_all_4Dnii_under_root_into_3Ds',...
'FG_combine_all_3Ds_series_under_root_into_4Ds',...
'FG_mat_into_hdr',...
'FG_viewnii_hi',...
'fprintf(''\n--- Select the subfunctions below...\n'')',...
'FG_voxbo_moveRawDICOM_to_root_matlab',...
'FG_category_DCM_by_protocol_names_n_subjs',...
'FG_convertDicom2Nifti_n_subjs',...
'FG_category_DCM_by_protocol_names',...
'FG_dicom_convert',...
'FG_convertDicom2Nifti_groups',...
'FG_check_DICOM_info',...
'FG_DICOMViewer',...
 'FG_load_nii',...
 'FG_load_untouch_nii',...
 'FG_load_nii_ext',...
 'FG_load_untouch_header_only',...
};

FGformat_L=[
[num2str(line_n) '. Image format related...'],...
'|  - Nii 2 (hdr/img)-pairs',...
'|  - (hdr/img)-pairs 2 Nii',...
'|  - Cluster_Img(hdr/img) 2 ROI.mat',...
'|  - ROI.mat 2 (hdr/img) to a target space',...
'|  - Get the 4D/3D nii volume number',...
'|  - Unzip (*.gz/*.nii.gz) files under a root recursively',...
'|  - Zip files(*.nii) into *.gz under a root recursively',...
'|  - 4D(.nii/.gz) -> 3Ds(nii) under a root recursively',...
'|  - 3Ds(nii) -> 4D(nii) under a root recursively',...
'|  - Merge *.mat data into *.hdr for SPM2 outputs',...
'|  - Nifti image Viewer',...
'|  - Matlab Voxbo-likewise functions for DICOM images',...
'|  - - Move Raw DICOMs to root-folder of subjects',...
'|  - - Categorize Dicom files into protocol folders(n-subjs)',...
'|  - - Dicom2Nifti(n-subjs)',...
'|  - Categorize Dicom files into protocol folders',...
'|  - Dicom2Nifti',...
'|  - Dicom2Nifti(n-Group-Subj)',...
'|  - Check header info of a DICOM img',...
'|  - Dicom image viewer',...
 '|  - FG_load_nii',...
 '|  - FG_load_untouch_nii',...
 '|  - FG_load_nii_ext',...
 '|  - FG_load_untouch_header_only',...
];

line_n=line_n+1;

% menu 7
f_rename={
'FG_change_folder_structure_for_GROCER',... 
'FG_remove_ScanNum_at_the_beginning_of_each_folder',... 
'FG_make_sameName_for_T1_in_sepfolder_nsubjs',... 
'FG_clean_T1_folder_after_selfmask_segment',... 
'FG_backconstruct_folder_structure_from_GROCER',... 
'FG_move_eachpair_into_sep_dir',... 
'FG_reorginaze_files_from_fullFactorial_to_flexiableFactorial',...
'FG_group_files_into_folders',...
'edit FG_file_group_identifier',...
'FG_group_files_into_folders_based_on_labeling',...
'edit FG_file_group_labels',...
'FG_rename_selected_files_multiDirs',...
'FG_rename_selected_dris',...
'FG_rename_selected_files',...
'FG_rename_selected_files_to_specified_names',...
'FG_get_allsubdirs_and_foldersize',...
'FG_list_allfolders_bigger_than_bytes',...
'FG_list_one_level_files',...
'FG_list_all_files',...
'FG_list_all_folders',...
'FG_list_files_subdirectory_by_subdirectory',...
'FG_readsubfolders',...
'FG_list_all_dirs_recursively',...
'FG_list_allfolders_bigger_than_bytes',...
'FG_get_save_filename_list',...
'FG_keep_filtered_files_or_folders',...
'FG_copy_folder_structure',...
'FG_copy_out_delete_in_with_same_folder_structure_fast',...
'FG_copy_out_delete_in_without_foderStructure',...
'FG_copy_out_delete_in_specific_size_folders',...
'FG_copy_out_delete_in_folders_with_same_folder_structure',...
'FG_copy_or_move_out_files_with_folder_name',...
'FG_move_subfolders_up_a_level_with_parent_folder_name',...
'FG_check_str_inTextfiles',...
'FG_find_and_replaceText',...
'FG_find_and_replaceText_multi_strs',...
'edit FG_example_search_and_replace_str',...
'FG_replace_strs_infile_WindowsOnly',...
'FG_excel_column_gen',...
'FG_randomly_split_two_groups',...
};

L_rename=[
[num2str(line_n) '. Files/folders manipulation...'],...
'|  * Restructure study folders for Grocer needed',...
'|  - - - Remove ScanNum at the beginning of each folder',... 
'|  - - - Make the names of all T1 imgs in Sep-Folders same',...
'|  - - - Clean T1 folder after selfmask-segment',... 
'|  - Backconstruct folder structure from Grocer needed',... 
'|  - Move Img(paired hdr/img & nii) into Sep.Subj folder',...
'|  - Reorganize files from full to flexible Factorial design',...
'|  - Group files into folders (n-Subjs)',...
'|  - - - Edit file identifiers',...
'|  - Group selected-files into folders based on labels',...
'|  - - - Edit file labels',...
'|  - Rename specific files under folder(s) (n-Subj)',...
'|  - Rename selected folders',...
'|  - Rename selected files',...
'|  - Rename selected files to predefined names',...
'|  - Get all subdir names and folder sizes',...
'|  - Get all subdir names having specific folder sizes',...
'|  - List files of a selected folder',...
'|  - List files of a dir recursively',...
'|  - List file-related folders of a dir recursively',...
'|  - List files subdirectory by subdirectory',...
'|  - List one-level subfolders under a dir',...
'|  - List all folders under of dir recursively',...
'|  - List all subfolders with specific folder-size',...
'|  - Get and save selected filenames of a dir',...
'|  - Del Non-filtered files/folders of a dir recursively',...
'|  - Copy the folder structure under a foder',...
'|  - Copy/Move-out/Del-in files recursively',...
'|  - Copy/Move-out/Del-in files recursively without folder Structure',...
'|  - Copy/Move-out/Del-in subdirs with folder-size',...
'|  - Copy/Move-out/Del-in filtered folders',...
'|  - Copy/Move-out files in subdirs with their folder name',...
'|  - Move filtered subdirs up a level with parent folder name',...
'|  - Check string in txt/m files',...
'|  - Find and replace in txt files',...
'|  - Find and replace Multi. strs in txt files',...
'|  - - - Edit Search & Replace strs template',...
'|  - Find and replace (Windows Only)',...
'|  - Generate Excel Column letters',...
'|  - Randomly split selected files/folders to two groups',...
];

line_n=line_n+1;

% menu 8
f_enhence={
'FG_batch_reset_origin',...
'FG_reset_origin_selectedImgs',...
'FG_reset_origin_selectedImgs_of_nSubjs',...
'FG_batch_reorient_T1s_origin',...
'FG_batch_reorient_allFun_origin',...
'FG_batch_resliceImg',...
'FG_reslice_Img_in_original_space',...
'FG_Reslice_multiplelabel_template',...
'FG_enhanced_spm_check_registration',...
'FG_stretch_two_imgs_after_check_reg',...
'FG_overlay_result_in_SPM_xjviewer',...
'FG_plot_realign_parameters',...
'FG_switch_red_arrow_ONandOFF_in_SPM',...
'FG_switch_crosshair_in_overlay_ONandOFF_in_SPM',...
'FG_flip_rl_ap_ud',...
'FG_overlay_ROI_on_ChechReg',...
'FG_overlay_RGB_on_ChechReg',...
'FG_VBM8_batch_gen',...
'edit FG_Create_VBM8_batch_parameters_default',...
'FG_snap_to_makeMovie',...
'FG_make_avimovie_for_mediaImgs',...

};

L_enhance=[
[num2str(line_n) '. SPM5/8 enhanced functions...'],...
'|  - Reset origins(n-Group-Subj)',...
'|  - Reset origins of selected Imgs',...
'|  - Reset origins of selected Imgs(n-Subj)',...
'|  - Reorient T1s',...
'|  - Reorient Fun. Imgs(n-Group-Subj)',...
'|  * Reslice selected Imgs into a target space',...
'|  - Reslice selected Imgs in original space',...
'|  - Reslice Multiple labeling template',...
'|  - Check-Reg up to 24 Imgs (paired-groups)',...
'|  - Enlarge the view of two Check-Reg Imgs',...
'|  - Overlay SPM_T/F Img to T1 by XjView',...
'|  - Plot the Realign_parameters(rp_*.txt)',...
'|  - Switch RedArrow ON/OFF in SPM Result Win.',...
'|  - Switch Crosshairs ON/OFF in SPM Result Win.',...
'|  - Flip images in original space',...
'|  - Overlay ROIs imgs on a Background img', ...
'|  - Overlay three ROI imgs on a Background img', ...
'|  - Create [Estimate and Write] batch for VBM8',...
'|  - - Edit and Create default parameters for VBM8 batch',...
'|  - Make avi-movie of a sequence of MRI-images',...
'|  - Make avi-movie of a sequence of Media-images',...
];

line_n=line_n+1;

% menu 9
funcs={
'FG_view_multiple_imgs_as_mricro',...
'FG_singledir_imgs_cal_gen_negative',...
'FG_img_pair_manipulation',...
'FG_singledir_imgs_cal_gen_Binary',...
'FG_multiG_imgs_cal_gen_Binary',...
'FG_singledir_imgs_cal_avgODD_and_even_separately',...
'FG_singledir_copyout_specific_imgs',...
'FG_multidirs_copyout_specific_imgs',...
'FG_singledir_imgs_cal_avgIntoSeparateLength_gen_run',...
'FG_multidirs_imgs_cal_avgIntoSeparateLength_gen_run',...
'FG_singledir_average_imgs_imgcal_gen',...
'FG_multiG_average_imgs_imgcal_gen',...
'FG_sum_GrayWhiteCSF_after_segment',...
'FG_sum_GrayWhite_to_create_individual_mask',...
'FG_view3d',...
'FG_view3d_variable',...
'fprintf(''\n--- Select the subfunctions below...\n'')',...
'FG_voxbo_moveRawDICOM_to_root_matlab',...
'FG_voxbo_vbrename_matlab',...
'FG_voxbo_vb2img_matlab',...
'FG_voxbo_vb2imgs_matlab',...
'edit FG_Output_folder_names',...
'FG_pca_denoising_or_DimReduction',...
'FG_linear_detrend_selected_imgs',...
'FG_linear_detrend_multiple_subjs',...
'FG_bandpass_filter',...
'FG_bandpass_filter_multiple_subjs',...
'FG_dice_similarity_coefficient_3D',...
'FG_dice_similarity_coefficient_3D_two_groups_revised',...
'FG_GCCA_multiDirs',...
'FG_GCCA_single',...
};

funcs_L=[
[num2str(line_n) '. Supplementary tools...'],...
'|  * Yoke displaying imgs as MRIcro',...
'|  - Manipulate(+,-,*,/) selected imgs(e.g. i1*-1)',...
'|  - Manipulate selected paired-imgs(e.g. (i1-i2)./i2)',...
'|  - Binarize the selected imgs(e.g. i1>0)',...
'|  - Binarize the selected imgs(e.g. i1>0)(n-Group-Subj)',...
'|  - Sum & Mean & Difference of the Odd/Even imgs',...
'|  - Copy out specific img series from selected imgs',...
'|  - Copy out specific img series (n-Group-Subj)',...
'|  - Avg selected imgs across same timepoints',...
'|  - Avg imgs across same timepoints (n-Group-Subj)',...
'|  - Average the selected images.',...
'|  - Average the images (n-Group-Subj)',...
'|  * Build brain masks from individual G.W.C.',...
'|  * Build brain masks from filled G.+ W.',...
'|  - Simple 3d image Viewer',...
'|  - Simple 3d-Variable Viewer',...
'|  - Basic Voxbo-tools for DICOM images(In-house use only)',...
'|  - - Move Raw DICOMs to root-folder of subjects',...
'|  - - vbrename for subjects',...
'|  - - vb2img for T1 folders',...
'|  - - vb2imgs for functional folders',...
'|  - - - Edit Output-functional-group-names',...
'|  - Testing: PCA img-denoising OR Var-Dim-Reduction',...
'|  - Linearly detrend the selected images',...
'|  - Linearly detrend for (n-Group-Subj)',...
'|  - Filter the selected images within the bandpass',...
'|  - Filter images of (n-Group-Subj) within the bandpass',...
'|  - Calculate the Dice similarity coefficient(selected imgs)',...
'|  - Calculate the Dice similarity coefficient(2-group of subjs)',...
'|  - [Testing]Granger Causal Connectivity Analysis (n-Subj)',...
'|  - Granger Causal Connectivity Analysis for selected imgs',...
];

line_n=line_n+1;

% menu 10
FGabout={
'[a,b,c,d]=FG_fileparts(which(''fmri_grocer.m''));open([a,filesep ''fmri_grocer_manual.htm''])',...
'[a,b,c,d]=FG_fileparts(which(''fmri_grocer.m''));open([a,filesep ''Examples_of_using_Grocer.htm''])',...
'uiwait(msgbox(sprintf(''                Grocer 2.17         \n\n Written by  Senhua Zhu  @ Upenn. Med.\n\n       E-mail:   zshtom@gmail.com\n            QQ group #: 60524357''),''Grocer 2.17'', ''help'',''modal''))',...
'FG_read_fun_lists_Grocer' ,...
'grocer_advance',...
};

about_L=[
[num2str(line_n) '. About...'],...
'|  - Quick start on this toolbox',...
'|  - Examples of using Grocer',...
'|  - About Grocer',...
'|  - Read the function list of Grocer',...
'|  ====  Advanced Grocer  ====    ',...
];


% line_n=line_n+1;



%% now setting up the PopUp menu in the Figure.
%=======================================================================  
% menu 1
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_preprocess,...
	  'Position',[bx by(1) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_preprocess);  
%=======================================================================  
% menu 2
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_statistic,...
	  'Position',[bx by(2) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_statistic);
%======================================================================= 
% menu 3
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_CBF,...
	  'Position',[bx by(3) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_CBF);
%=======================================================================  
% menu 4
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_ROI,...
	  'Position',[bx by(4) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_ROI);
%=======================================================================  
% menu 5
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_Coordinate,...
	  'Position',[bx by(5) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_Coordinate);  

%=======================================================================  
% menu 6
uicontrol(Fig_handle,'Style','PopUp',...
      'String',FGformat_L,...
      'Position',[bx by(6) bw bh].*WS,...
      'ToolTipString','SPM8 related batch works...',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',FGformat);    
  
%=======================================================================  
% menu 7 
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_rename,...
	  'Position',[bx by(7) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_rename);
%=======================================================================  
% menu 8
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',L_enhance,...
	  'Position',[bx by(8) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',f_enhence);
%=======================================================================  
% menu 9
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',funcs_L,...
	  'Position',[bx by(9) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',funcs);
  
%=======================================================================  
% menu 10
uicontrol(Fig_handle,'Style','PopUp',...
	  'String',about_L,...
	  'Position',[bx by(10) bw bh].*WS,...
	  'ToolTipString','SPM8 related batch works...',...
	  'CallBack','spm(''PopUpCB'',gcbo)',...
	  'UserData',FGabout);  
  

%=setting up some buttons =  
%=======================================================================
% button 11 == standby button
uicontrol(gcf,'String','Panel standby',...
	  'Position',[bx+20 by(10)*0.68 bw*0.4 bh*0.6].*WS,...
	  'ToolTipString','small this panel and set it on top',...
	  'ForeGroundColor',[0.8 0.3 0],...
	  'FontSize',FS(10),...
      'FontWeight','BOLD',...
      'Tag','standby_b',...
      'Interruptible','off',...
	  'CallBack',@Exec_standby); % be careful:  "@" means Function handle.
%=======================================================================
% button 12 == recover button
uicontrol(gcf,'String','Panel recover',...
	  'Position',[bx+20 by(11)*0.6+2 bw*0.4 bh*0.6].*WS,...
	  'ToolTipString','recover this panel',...
	  'ForeGroundColor',[0.5 0.2 0],...
	  'FontWeight','BOLD',...
      'FontSize',FS(10),...
      'Interruptible','off',...
	  'CallBack',@Exec_recover);  
%=======================================================================
% button 21 == Run all jobs button
uicontrol(gcf,'String','Run selected jobs',...
	  'Position',[bx+bw*0.6-20 by(10)*0.68 bw*0.4 bh*0.6].*WS,...
	  'ToolTipString','Select jobs & Run them',...
	  'ForeGroundColor','r',...
	  'FontWeight','BOLD',...
      'FontSize',FS(10),...
      'Tag','run_b',...      
      'Interruptible','off',...
	  'CallBack','FG_run_all_jobs');  
%=======================================================================
% button 22 == quit button
uicontrol(gcf,'String','Exit',...
	  'Position',[bx+bw*0.6-20 by(11)*0.6+2 bw*0.4 bh*0.6].*WS,...
	  'ToolTipString','exit the fmri_grocer',...
	  'ForeGroundColor','b',...
      'FontSize',FS(12),...
	  'FontWeight','BOLD',...
      'Interruptible','off',...
	  'CallBack',@Exit_goodbye);


%=======================================================================
% after drawing the figure, set it into visible and on top
set(Fig_handle,'Visible','on')
% FG_setAlwaysOnTop(gcf,1);


%--------------------------------------
%=======    subfunctions    ==========
%--------------------------------------
function  [WS FS PF Rect bno bgapr bh gh by bx bw]=Exec_getwinDef   
        WS   = spm('WinScale');				%-Window scaling factors, Returns ratios of current display dimensions to that of a 1152 x 900
        FS   = spm('FontSizes');			%-Scaled font sizes
        PF   = spm_platform('fonts');			%-Font names (for this platform)
        screenxy=get(0,'ScreenSize');  % four element:screenxy ==>[left, bottom, width, height]
        Rect = [1/4*screenxy(3) 290 400 475];
       % Rect = [1/4*screenxy(3) 1/5*screenxy(4) 1/4*screenxy(3) 1/2.3*screenxy(4)];   %-Raw size menu window; rect = [left, bottom, width, height]
        bno = 11; bgno = bno+1; % bno= button num, bgno=button_gap num
        bgapr = 0.10; %  button gap ratio
        bh = Rect(4) / (bno + bgno*bgapr);      % Button height
        gh = bh * bgapr;                        % Button gap height
        by = fliplr(cumsum([0 ones(1, bno-1)*(bh+gh)])+gh);
        bx = Rect(3)*0.02;
        bw = Rect(3)*0.96;
        
function  Exec_standby(hObject,eventdata)   % "hObject" is the handle of the [callback] object, "eventdata" (see next function)
        [WS FS PF Rect bno bgapr bh gh by bx bw]=Exec_getwinDef;
        %Fig_handle=findobj('Tag','fmri_grocer');
        set(gcf,'Position',[0 0 Rect(3)*WS(3) bh*0.5+10]);
        h_std=findobj('Tag','standby_b');
        h_run=findobj('Tag','run_b');
        set(h_std,'Visible','off');
        set(h_run,'Visible','off');
        FG_setAlwaysOnTop(gcf,1);  
        
        
function  Exec_recover(hObject,eventdata)   % while "eventdata" is just an unused variable for the function handle purpose
        [WS FS PF Rect bno bgapr bh gh by bx bw]=Exec_getwinDef;
        %Fig_handle=findobj('Tag','fmri_grocer');
        set(gcf,'Resize','off');
        set(gcf,'Position',Rect.*WS);
        h_std=findobj('Tag','standby_b');
        h_run=findobj('Tag','run_b');
        set(h_std,'Visible','on');
        set(h_run,'Visible','on');
        FG_setAlwaysOnTop(gcf,0);

function Exit_goodbye(hObject,eventdata)
       FGver = '2.17';
       close;clc; 
       fprintf('\n')
      
       fprintf( '\n-----------------------------------------------------  V%s --------------------------------------\n',FGver)
       fprintf( '-------------00000000000----------------------- QQ group #: 60524357 ------------------------------\n')
       fprintf( '----------000000000000000-------------------  ^_^ Have a good one ^_^  ----------------------------\n')
       fprintf( '---------000000----000000--------------------------------------------------------------------------\n')
       fprintf( '-------0000000     00000---00000000-------0000000------00000000-----00000000------0000000----------\n')
       fprintf( '-------00000              000000000000  00000000000   00000000000 000000000000  000000000000-------\n')
       fprintf( '------00000               00000000000  0000     000 0000     000 0000     0000  00000000000--------\n')
       fprintf( '------00000     0000000   000000      0000      000 0000        00000000000000  000000   ----------\n')
       fprintf( '----- 00000      000000   00000      0000       000 0000        0000000000000   00000--------------\n')
       fprintf( '------00000      00000   000000      0000      0000 0000        0000            00000--------------\n')
       fprintf( '------00000     00000   0000000      0000     0000  0000    000 00000    000   000000--------------\n')
       fprintf( '-------000000000000----000000000------00000000000----000000000---0000000000---00000000-------------\n')
       fprintf( '--------000000000------000000000-------0000000--------0000000------000000-----00000000-------------\n')
       fprintf( '---------------------------------------------------------------------------------------------------\n');                  
